const InfoError = {
    'vuoto': 'Campo vuoto',
    'data': 'Inserire una data superiore a quella corrente',
    'data_2': 'Inserire una data inferiore a quella corrente',
    'genere': 'Inserire un Genere valido',
    'regista': 'Inserire un Regista valido',
    'attore': 'Inserire un Attore valido',
    'caratteri': 'Inserire caratteri validi',
    'img': 'Inserire un URL valido',
    'limite_caratteri': 'Superato il limite massimo di caratteri consentiti',
    'password': 'Inserire almeno 8 caratteri',
    'confirm_password': 'Le password non corrispondono',
    'comune':'Inserire un comune valido',
    'pt_vendita':'Inserire un punto vendita valido',
    'fornitore':'Inserire un fornitore valido',
    'cliente':'Inserire un cliente valido',
    'film':'Inserire un film valido',
    'file': 'Allegare un file valido',
    'caratteri_min': 'Inserire almeno 2 caratteri',
    'iva': 'La partita IVA in genere è composta da 11 cifre',
    'cap':'Il CAP in genere è composto da almeno 5 cifre',
    'telefono': 'Il numero di telefono in genere è composto da almeno 8 cifre',
    'numero': 'Inserire un numero valido',
    'numero_2': 'Inserire un numero maggiore di zero',
    'email_1': 'l\'email in genere è composta da almeno 8 caratteri',
    'email_2': 'email non valida',
    'ingredienti': 'Inserire almeno un ingrediente'
  }

  export default InfoError;
